name: Trivy Scan

on: [push]

jobs:
  trivy_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trivy Scan
        run: |
          ./trivy_scan_script.sh
